server:
  port: 8082

spring:
  application:
    name: best-project-product
  datasource:
    url: jdbc:mysql://localhost:3306/bp_product?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zws812000

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
  global-config:
    db-config:
      logic-delete-field: deleteAt  # 逻辑删除字段（数据库字段名 delete_at）
      logic-delete-value: "NOW()"   # 逻辑删除时存储当前时间
      logic-not-delete-value: "NULL"  # 逻辑未删除时字段值

#多租户配置，默认不开启
#mybatis-tenant:
#  enable: true

logging:
  level:
    com.zhangweisen.best.project: debug

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zhangweisen.best.project.product.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn